/**
 * Template registry.
 *
 * Templates are plain strings with `{{var}}` placeholders, rendered by
 * `render()`. Keeping templates as string exports (instead of separate .md
 * files on disk) means they ship inside the published tarball and survive
 * bundling without a runtime asset resolver.
 */

export interface TemplateVars {
  [key: string]: string | number | boolean | undefined;
}

export function render(template: string, vars: TemplateVars): string {
  return template.replace(/{{\s*([\w.]+)\s*}}/g, (_, key) => {
    const v = vars[key];
    return v === undefined || v === null ? "" : String(v);
  });
}

// ---- Root files ------------------------------------------------------------

export const CLAUDE_MD = `# CLAUDE.md

> Project context for Claude Code. Generated by claude-bootstrap. Re-run \`npx @themohitgaur1/claude-bootstrap sync\` after major changes.

## Project: {{projectName}}

- **Type:** {{repoType}}
- **Primary frameworks:** {{frameworks}}
- **Package manager:** {{packageManager}}
- **Architecture style:** {{architectureStyle}}

## How to work in this repo

1. Read \`AGENTS.md\` first for the cross-tool rules every agent must follow.
2. Read \`.ai/knowledge/ARCHITECTURE.md\` before non-trivial changes.
3. Prefer the slash commands in \`.claude/commands/\` for routine work.
4. Delegate to subagents in \`.claude/agents/\` when a task crosses domains.

## Code conventions

- Match existing patterns. Read 2-3 nearby files before writing new ones.
- Never invent dependencies. Check \`package.json\` first.
- Tests live in \`{{testsPath}}\`. Run them after meaningful changes.

## Off-limits

- Do not edit generated files in \`.ai/\` or \`.claude/\` directly  Ere-run \`sync\`.
- Do not commit secrets. Use the project's secret manager.
`;

export const AGENTS_MD = `# AGENTS.md

> Cross-tool agent contract  Eread by Claude, Cursor, Gemini CLI, Copilot, Aider, etc.

## Project: {{projectName}}

This file is the single source of truth for **how AI agents behave in this repo**.
Tool-specific files (\`CLAUDE.md\`, \`.cursorrules\`, etc.) extend  Enever contradict  Ethis file.

## Repository

- Type: {{repoType}}
- Frameworks: {{frameworks}}
- Package manager: {{packageManager}}

## Rules every agent MUST follow

1. **Understand before changing.** Read existing files. Match the patterns you see.
2. **Small, reviewable changes.** One concern per change. No drive-by refactors.
3. **Tests are not optional.** If the change is testable, write or update the test.
4. **Never invent APIs.** If a function/lib doesn't exist, say so  Edon't fabricate.
5. **Ask when ambiguous.** A clarifying question beats a wrong implementation.
6. **Respect secrets.** Never read or print env values. Never commit \`.env*\`.

## Project-specific guidance

See \`.ai/knowledge/\` for ARCHITECTURE, AUTHENTICATION, DATABASE, API_GUIDELINES, WORKFLOWS, BUSINESS_RULES.
`;

// ---- Agents ----------------------------------------------------------------

export const AGENT_MD = `---
name: {{name}}
description: {{description}}
tools: {{tools}}
---

# {{title}}

## Role

{{role}}

## Responsibilities

{{responsibilities}}

## How to operate

- Always read \`AGENTS.md\` first.
- Stay inside your domain. Hand off to another subagent when the task crosses boundaries.
- When in doubt, output a question rather than a guess.
`;

// ---- Commands --------------------------------------------------------------

export const COMMAND_MD = `---
description: {{description}}
---

# /{{name}}

{{body}}
`;

// ---- Hooks (shell scripts) -------------------------------------------------

export const HOOK_SH = `#!/usr/bin/env bash
# {{name}} hook  Egenerated by claude-bootstrap
# Trigger: {{trigger}}
set -euo pipefail

{{body}}
`;

// ---- Skills ----------------------------------------------------------------

export const SKILL_MD = `---
name: {{name}}
description: {{description}}
---

# {{title}}

## When to use

{{whenToUse}}

## Best practices

{{bestPractices}}

## Common patterns

{{patterns}}

## References

{{references}}
`;

// ---- MCP -------------------------------------------------------------------

export const MCP_CONFIG_JSON = `{
  "mcpServers": {{servers}}
}
`;

// ---- Knowledge -------------------------------------------------------------

export const KNOWLEDGE_MD = `# {{title}}

> {{subtitle}}

{{body}}

---

_Generated by claude-bootstrap. Edit manually, then run \`npx @themohitgaur1/claude-bootstrap sync --preserve\` to keep your edits._
`;

// ---- Settings --------------------------------------------------------------

export const SETTINGS_JSON = `{
  "$schema": "https://json.schemastore.org/claude-code-settings",
  "permissions": {
    "allow": ["Read", "Edit", "Write", "Bash(pnpm:*)", "Bash(npm:*)", "Bash(git:*)"],
    "deny": ["Bash(rm -rf:*)", "Read(./.env*)"]
  },
  "hooks": {
    "PreToolUse": [],
    "PostToolUse": [],
    "TaskCompleted": [],
    "SubagentStop": []
  }
}
`;
